name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies and set path
        run: |
            sudo apt-get update
            sudo apt-get install -y ninja-build libcunit1-dev  python3-pip
            # Install meson as root so we can install to the system below.
            sudo pip install meson
      - name: Build tarball
        run: |
          cd c
          rm test-data
          cp -r ../test-data .
          meson . ../build-gcc
          cd ../build-gcc
          git config --global user.email "CI@CI.com"
          git config --global user.name "Mr Robot"
          git add -A
          git commit -m "dummy commit to make meson add in the symlinked directory"
          meson dist
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && contains(github.event.ref, 'C_')
        with:
          draft: True
          files: build-gcc/meson-dist/*